/*Implement a PL/SQL block with a cursor to fetch and display the Name and Salary of the
top 5 highest-paid employees from the Staff table.*/

CREATE TABLE STAFF (
    STAFF_ID NUMBER PRIMARY KEY,
    STAFF_NAME VARCHAR2(100),
    STAFF_SALARY NUMBER(10,2)
);

INSERT INTO STAFF VALUES (101, 'Rahul', 50000);
INSERT INTO STAFF VALUES (102, 'Amit', 60000);
INSERT INTO STAFF VALUES (103, 'Priya', 45000);
INSERT INTO STAFF VALUES (104, 'Rishi', 61000);
INSERT INTO STAFF VALUES (105, 'Kridha', 78000);
INSERT INTO STAFF VALUES (106, 'Payal', 35000);
INSERT INTO STAFF VALUES (107, 'Ritu', 51000);
INSERT INTO STAFF VALUES (108, 'Gitika', 60600);
INSERT INTO STAFF VALUES (109, 'Chhavi', 43000);

SELECT * FROM STAFF;

DECLARE
CURSOR stf_cursor IS SELECT STAFF_ID, STAFF_NAME, STAFF_SALARY FROM STAFF ORDER BY STAFF_SALARY DESC;

V_STAFF_ID STAFF.STAFF_ID%TYPE;
V_STAFF_NAME STAFF.STAFF_NAME%TYPE;
V_STAFF_SALARY STAFF.STAFF_SALARY%TYPE;

V_COUNT NUMBER:=0;

BEGIN
    OPEN stf_cursor;
    FETCH stf_cursor INTO V_STAFF_ID, V_STAFF_NAME, V_STAFF_SALARY;

    WHILE (stf_cursor%FOUND AND V_COUNT<5)
    LOOP
        DBMS_OUTPUT.PUT_LINE('ID: ' || V_STAFF_ID || 
        ' NAME: ' || V_STAFF_NAME || ' SALARY: ' || V_STAFF_SALARY);
        V_COUNT:=V_COUNT+1;

        FETCH stf_cursor INTO V_STAFF_ID, V_STAFF_NAME, V_STAFF_SALARY;

    END LOOP;

    CLOSE stf_cursor;
END;
