--if then else 
DO $$
DECLARE
AGE INT:=19;
BEGIN
IF AGE>=18 THEN 
RAISE NOTICE 'YOUR AGE IS % AND YOU ARE ELIGIBLE TO VOTE', AGE;
ELSE
RAISE NOTICE 'YOUR AGE IS % AND YOU ARE NOT ELIGIBLE TO VOTE', AGE;
END IF;
END;
$$

--if then elsif ladder
DO $$
DECLARE
VAL INT:=19;
BEGIN
IF VAL>=1 AND VAL<=10 THEN 
RAISE NOTICE 'YOUR VALUE IS % AND LIES BETWEEN THE RANGE 1-10', VAL;
ELSIF VAL>10 AND VAL<=20 THEN
RAISE NOTICE 'YOUR VALUE IS % AND LIES BETWEEN THE RANGE 11-20', VAL;
ELSIF VAL>20 AND VAL<=30 THEN
RAISE NOTICE 'YOUR VALUE IS % AND LIES BETWEEN THE RANGE 21-30', VAL;
ELSE 
RAISE NOTICE 'YOUR VALUE IS % AND GREATER THAN 30', VAL;
END IF;
END;
$$
